"""created relationships"


Revision ID: 2b259e5ca16b
Revises: 37d0047589d1
Create Date: 2024-05-14 10:54:18.899780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b259e5ca16b'
down_revision = '37d0047589d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
